### ISSUE TITLE
Problems with metadata

### ISSUE THREAD

**Issue by attilamolnar** [ircv3/ircv3-specifications#219] opened 2016-02-11 12:45 UTC
These problems were discussed on IRC in January, summary by @rburchell:
1. There’s no spec for restriction of values. Servers should have freedom to reject client-set values (e.g. filtered content, and so on)
   Idea: This may need a new numeric for rejection of values for server-side reasons
2. Metadata lists (RPL_KEYVALUE) are incredibly verbose with significant amounts of metadata. Ideally, listing metadata should come in as few a set of messages as possible (it’s flawed in other ways, but think of RPL_NAMEREPLY and friends) to limit bandwidth use.
   Comment: May need a new transport protocol or limitations on keys/values. Perhaps we just accept this as a limitation of the protocol and move on with life.
3. Clients may want to recieve metadata notifications for only certain keys. Not every key is interesting to clients. Picture for instance client avatars: a nicklist needs these. so on join, having them is useful. Knowing the user’s postal address or phone number on join is not so useful.
   Idea: introduce a way to request _what_ keys you’re interested in. `METADATA SYNC <Target> <Key>[,<Key>]`?
4. The requirement to get metadata for all neighbours introduces the capability for significant bandwidth use.
   Idea: see 3. This at least limits the amount of bandwidth consumption. Combined with a new channel burst/protocol transport, this should be fairly negligable. In addition, metadata-notify SHOULD probably be limited to specified keys that do find it useful. `METADATA SYNC` could have error codes that would disallow subscription to too many (or unknown) keys.
5. “Clients SHOULD have current metadata of targets propagated to them upon subscription.”
   Combined with metadata-notify on all members of channels, this has the potential to result in huge amounts of bandwidth use by toggling metadata-notify. Disabling should be disallowed.

**Comment by Aerdan** [comment] 2016-02-11 17:45
1. This is a policy problem, not a technical problem. However, numeric `763` is available for this purpose.

2. This is a protocol-level issue and needs to be addressed at that level. Unfortunately, the last two attempts at defining an alternative to RFC 1459's message format have stalled.

3. Clients are free to silently ignore keys they don't care about. This is no different from any other kind of event which wants filtering. Putting the job of filtering on the server is a bad idea.

4. If bandwidth issues are a serious consideration, either don't request `metadata-notify` or don't have it enabled on the server. Metadata notifications solve a number of polling-based issues, particularly with respect to fields in `WHOIS`.

5. See above. Additionally, clients who have `metadata-notify` enabled and want to monitor particular users need to have the current state propagated in order for metadata-related functions implemented client-side to operate properly. The server can't know what those are, and certainly this working group can't either.

**Comment by ChickenNuggers** [comment] 2016-02-11 17:48
> If bandwidth issues are a serious consideration, either don't request metadata-notify or don't have it enabled on the server. Metadata notifications solve a number of polling-based issues, particularly with respect to fields in WHOIS.

Is this honestly a proper solution? What if we want to enable metadata?

**Comment by attilamolnar** [comment] 2016-02-11 17:48
No, it's not a proper solution. The metadata spec also does not say whether metadata-notify is optional or not.

**Comment by ChickenNuggers** [comment] 2016-02-11 17:50
> Clients are free to silently ignore keys they don't care about. This is no different from any other kind of event which wants filtering. Putting the job of filtering on the server is a bad idea.

Bandwidth most times is more valuable than the amount of processing it takes to filter.

**Comment by attilamolnar** [comment] 2016-02-11 18:02
> 1. This is a policy problem, not a technical problem. However, numeric `763` is available for this purpose.

This is a technical problem because there is no way to signal "this value is unacceptable" to a client. Numeric 763 is not in the specification.

**Comment by Aerdan** [comment] 2016-02-11 18:17
> Bandwidth most times is more valuable than the amount of processing it takes to filter.
>> If bandwidth issues are a serious consideration, either don't request metadata-notify or don't have it enabled on the server. Metadata notifications solve a number of polling-based issues, particularly with respect to fields in `WHOIS`.
> Is this honestly a proper solution? What if we want to enable metadata?

Given that IRC is presently one of the least-intensive protocols for bandwidth, it's probably more appropriate to consider flood-control mechanisms than it is to consider bandwidth-minimization issues, particularly since at present flood-control is already an expected part of server implementations. I regard bandwidth minimization as a premature optimization at this stage, in any event.

> This is a technical problem because there is no way to signal "this value is unacceptable" to a client. Numeric 763 is not in the specification.

Filtering is a policy problem and should be resolved with policy, not with technical solutions. I suggested numeric `763` because it's not presently allocated and therefore is free for providing a technical aid for the purpose of notifying users of policy-related alterations or rejections. In short, I am proposing that, because this particular issue is a policy problem, the solution be implementation-defined.

**Comment by kaniini** [comment] 2016-02-11 20:40
@Aerdan the problem isnt with bandwidth consumption, it's memory (sendq) consumption.  You could flood users off with sendq exceeded.

**Comment by Aerdan** [comment] 2016-02-11 21:44
Oh. Well, in that case...

I'm not sure I like `SYNC`; people have asked for a way to mute keys of non-interest before, so it seems better to integrate that request. Would `PRIORITY <priority> <key> <key2> ... <keyn>` suffice? (Where `<priority>` is one of `sub` (on subscription), `change` (on change), or `request` (only when the client requests it explicitly).)

**Comment by dequis** [comment] 2016-02-12 00:14
>Where `<priority>` is one of `sub` (on subscription),

Joining a channel and getting initial metadata notifications but not their changes isn't really a subscription, it's just a poll initiated by the server. It would be nice if that case could by handled by doing a bulk request of metadata keys of a channel when joining it, just like clients do an initial sync with WHOX, but for a specific set of metadata keys.

Sorta like `METADATA #channel/* GET key1 key2 key3`, and pretend that the `/*` suffix isn't valid for channels. I guess a different verb might be a better solution, might even help to apply rate limits too.

So the subscription status could be an on/off toggle, and if a client only cares about a set of keys when joining, it can poll them that way.

**Comment by Aerdan** [comment] 2016-02-12 00:17
Sorry, I should clarify: `sub` implies `change`—I can't think of any circumstances where it'd be useful to do initial state propagation without following with change propagation.

**Comment by dequis** [comment] 2016-02-12 00:30
Oh uh. Well. That's a good point. Now I don't see the point of what i just suggested.

I still like the idea of a client-initiated bulk get, although I'm not sure if it's worth changing at this point. Some clients decide whether to send `WHO` and others based on the amount of people joined to a channel, for example, and might decide to skip `METADATA GET` (and `WHO`) in large channels. But that's also something the server may decide to do.

If we keep the initial metadata sync up to the server then aerdan's idea is fine.

**Comment by jwheare** [comment] 2016-11-18 15:06
These are being addressed in #250 and #245

**Closed by jwheare** 2016-11-18 15:06 UTC
