### ISSUE TITLE
3.3: tags shouldn't require caps, and echo-message

### ISSUE THREAD

**Issue by kaniini** [ircv3/ircv3-specifications#187] opened 2015-12-04 18:14 UTC
I would like to propose that:

  * echo-message becomes a sticky/required capability for 3.3 implementations
  * 3.3 implementations can send whatever tags they want (and frankly if your client cannot handle unanticipated tags you've really managed to screw it up anyway)

if this is an acceptable proposal, I will write a spec codifying both.

**Comment by grawity** [comment] 2015-12-04 18:18
Required sounds fine, though how do you enforce sticky? Does the client send its claimed supported version?

Arbitrary tags sound okay, afaik the original reason was just to let caps specify which tags are server-sent & can be trusted vs which are end-to-end. I guess that's no longer relevant with data- tags though.

**Comment by kaniini** [comment] 2015-12-04 18:19
Well, since we know data-tags are bullshit, data-tags should not require a cap.  If that makes sense.

I'm not sure how to enforce it, I guess that doesn't matter.  We just make it required and call it a day.

**Comment by dequis** [comment] 2015-12-04 18:31
>Does the client send its claimed supported version?

This is pretty much the approach the `CAP LS 303` PR was taking.

>since we know data-tags are bullshit

Data tags aren't just a way to workaround the requirement that each tag should have a cap (although they were designed around the idea that this requirement won't change), they also cover the case of sending something from one client to all the others without any server-side processing, what grawity mentioned as "end-to-end"

**Comment by SaberUK** [comment] 2015-12-05 16:45
>3.3 implementations can send whatever tags they want (and frankly if your client cannot handle unanticipated tags you've really managed to screw it up anyway)

Breaking clients which don't support the IRCv3.2 message format sounds like a terrible idea.

**Comment by kythyria** [comment] 2015-12-05 16:50
@SaberUK I think the idea is that clients that have indicated to the server support for 3.3 (or 3.2, really) not break on encountering unanticipated tags. Come to think of it, how the heck would you build a client that *doesn't* have that property?

**Comment by SaberUK** [comment] 2015-12-05 16:56
`CAP LS 302` only indicates that the client supports CAP 3.2. Its possible for an implementation to support CAP 3.2 (which is only a small amendment) without supporting message tags (which requires the message parser to be rewritten).

**Comment by SaberUK** [comment] 2015-12-05 16:59
The best way in my opinion would be to introduce a `message-format=rfc1459,ircv32` cap and the client can REQ the version they support. This would also be useful for in the future if we want to move to JSON.

**Comment by Mikaela** [comment] 2015-12-06 12:13
> echo-message becomes a sticky/required capability for 3.3 implementations

:+1:, this would probably also fix https://github.com/ircv3/ircv3-specifications/issues/182 or at least make it clear that the issue is entirely client-side not supporting echo-message and people complaining about it can be sent to issue trackers of their clients.

> 3.3 implementations can send whatever tags they want (and frankly if your client cannot handle unanticipated tags you've really managed to screw it up anyway)

I have no opinion on this and I fear I don't fully understand this part. What should I read to learn more about this?

**Comment by jwheare** [comment] 2016-03-07 11:37
Tags not requiring caps is addressed by #236.

What is the motivation for making echo-message implicitly enabled by `CAP LS 303`?

**Comment by dequis** [comment] 2016-03-07 17:37
@jwheare it's similar in spirit to how #170 implicitly enables self-message.

>### Self-messages
>
>Clients that receive self-sent PRIVMSG and NOTICE messages, MUST treat them the same way as if the client itself would have sent the message to the target.
>
>The purpose of this requirement is to allow clients receive full chat history, that may include their own messages, without having to request the echo-message capability that requires special handling on the client side.

Replacing the self-message cap with echo-message was a mistake, the current situation is a mess. Back when that decision was made I thought incorrectly that the only client that handled it wrong was irssi (which is fixed now), but there are other clients that always handled it wrong and still do

**Comment by jwheare** [comment] 2016-03-08 09:50
echo-message cannot be a required CAP to avoid the double message issue raised in #170. self-message can be, but it no longer exists, except as znc.in/self-message. So I'm closing this issue because it's too confusing and half of it is dealt with elsewhere. The echo/self-message situation can be discussed in a new ticket if needed that explains everything from scratch.

**Closed by jwheare** 2016-03-08 09:50 UTC
